# Generated by Django 3.0.1 on 2019-12-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of Grooming Report')),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name of the resort')),
                ('location', models.CharField(max_length=1000, verbose_name='Location of the resort')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name of the run')),
                ('difficulty', models.CharField(max_length=100, verbose_name='Difficulty of run, green/blue/black')),
                ('report', models.ManyToManyField(to='reports.Report')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Resort')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Resort'),
        ),
    ]
