# Generated by Django 3.0.1 on 2019-12-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Location of the resort'),
        ),
    ]
