# Generated by Django 3.0.1 on 2019-12-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20191224_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='report_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL to grooming report'),
        ),
    ]
