# Generated by Django 3.0.1 on 2019-12-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_resort_report_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='difficulty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Difficulty of run, green/blue/black'),
        ),
    ]
