# Generated by Django 3.0.1 on 2019-12-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20191224_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='Date of Grooming Report'),
        ),
    ]
