# Generated by Django 3.0.1 on 2019-12-30 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20191225_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Report')),
                ('full_report', models.ManyToManyField(related_name='hd_report', to='reports.Report')),
                ('runs', models.ManyToManyField(to='reports.Run')),
            ],
            bases=('reports.report',),
        ),
    ]
